mod: debug
database:
  addr: mongodb://mongo:27017 # mongo数据库地址
  # addr: mongodb://localhost:27017 # mongo数据库地址
  db: sip
udp: 0.0.0.0:5060 # sip服务器udp端口
api: 0.0.0.0:8090 # sip服务 restfulapi 端口
secret: z9hG4bK1233983766 # restful接口验证key 验证请求使用
logger: debug
media:
  restful: http://mediaserver:80 # media 服务器restfulapi地址 
  http: http://192.168.1.90:8080  # media 服务器 http请求地址
  WS: ws://192.168.1.90:8080  # media 服务器 ws请求地址
  rtmp: rtmp://192.168.1.90:1935  # media 服务器 rtmp请求地址
  rtsp: rtsp://192.168.1.90:8554   # media 服务器 rtsp请求地址
  rtp: http://192.168.1.90:10000  # media rtp请求地址 zlm对外开放的接受rtp推流的地址
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc # zlm secret key 用来请求zlm接口验证
stream:
  hls: 1 # 是否开启视频流转hls
  rtmp: 1 # 是否开启视频流转rtmp
gb28181: # gb28181 域，系统id，用户id，通道id，用户数量，初次运行使用配置，之后保存数据库，如果数据库不存在使用配置文件内容
  lid:    "37070000082008000001" # 系统ID
  region: 3707000008           # 系统域
  uid:    37070000081118       # 用户NVR设备前缀
  did:    37070000081318       # 通道设备前缀
  unum:   0 # 用户id = uid + unum
  dnum:   0 # 通道id = did + dnum
record:
  recordmax: 20 # 视频录制最长时间，-1表示不限制，不设置或0默认10分钟，单位秒。到时间后自动停止录制
  filepath: /usr/share/zlm/meida # zlm 不会自动清理录制文件，需要配置录像文件路径和定时清理时间。
  expire: 5 # 录制文件录制完成后多久删除，单位天，不设置默认7天。
notify:  
  users_active: http://localhost:1122/user/active # 用户NVR设备活跃通知
  devices_active: http://localhost:1122/user/active # 通道设备活跃通知
  users_regiest: http://localhost:1122/user/active # 用户设备注册成功通知
  records_stop: http://localhost:1122/user/active # 录制文件录制完成通知  一定要配置zlm的webhook地址为此项目sip服务的restfulapi端口地址，否则录制存在问题。

