# Use postgres/example user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27027:27017"
    volumes:
      - /opt/dockerdata/mongo:/data/db # 本地创建/opt/dockerdata/mongo目录
    networks:
      base:
        aliases:
          - mongo

  sipserver:
    image: panjjo/sipserver:1.0.0
    restart: always
    ports:
      - "8090:8090" # restful api端口
      - 5060:5060/udp # sip服务信令端口
    volumes:
      - /opt/dockerdata/media/www:/meida/www # 本地创建/opt/dockerdata/media/www 用来存在视频文件
    environment:
      LOGGER: trace
      MEDIA_RESTFUL: http://mediaserver:80 # 媒体服务器接口地址，不需要改动
      DATABASE_ADDR: mongodb://mongo:27017/?connect=direct # mongo地址，不需要改动
      NOTIFY_USERS_ACTIVE: http://xxxxx # 用户设备活跃通知地址（心跳），自行配置
      NOTIFY_DEVICES_ACTIVE: http://xxxxx # 通道设备活跃通知地址（心跳）自行配置
      NOTIFY_USERS_REGIEST: http://xxxxx # 用户设备注册成功通知地址， 自行配置
      NOTIFY_RECORDS_STOP:  http://xxxxx # 录制自动停止通知地址，自行配置
      MEDIA_HTTP: http://xxxxx # 媒体播放地址，根据自己环境配置，可以直接播放的视频地址，请求转到mediaserver的http端口
      MEDIA_RTP: http://xxxxx:xxxx # GB28181接受RTP视频流的地址，IP+端口号方式，端口号使用mediaserver中暴漏的RTP端口
    networks:
      base:
        aliases:
          - sipserver

  mediaserver:
    image: panjjo/zlmediakit
    restart: always
    ports: 
      - 1935:1935
      - 8080:80  # 媒体服务队外暴露的http请求端口
      - 8554:554 
      - 10000:10000 # 媒体服务暴露出来接受RTP视频流的端口
      - 10000:10000/udp #媒体服务暴露出来接受RTP视频流的端口
    volumes:
      - /opt/dockerdata/media/config.ini:/zlmediakit/config.ini # 媒体服务配置文件本地挂载路径
      - /opt/dockerdata/media/www:/zlmediakit/www # 媒体服务视频存储目录
    networks:
      base:
        aliases:
          - mediaserver
networks:
  base:
    driver: bridge
